import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

export default function ReportsPage() {
  const [stats, setStats] = useState({ total: 0, open: 0, closed: 0, overdue: 0 })
    const [byType, setByType] = useState([])
      const [loading, setLoading] = useState(true)

        useEffect(() => {
            const load = async () => {
                  const { data } = await supabase.from('complaints').select('status, complaint_type, due_date')
                        if (data) {
                                const now = new Date()
                                        setStats({
                                                  total: data.length,
                                                            open: data.filter(c => c.status !== 'closed').length,
                                                                      closed: data.filter(c => c.status === 'closed').length,
                                                                                overdue: data.filter(c => c.status !== 'closed' && c.due_date && new Date(c.due_date) < now).length,
                                                                                        })
                                                                                                const types = {}
                                                                                                        data.forEach(c => { types[c.complaint_type || 'Unknown'] = (types[c.complaint_type || 'Unknown'] || 0) + 1 })
                                                                                                                setByType(Object.entries(types).map(([type, count]) => ({ type, count })))
                                                                                                                      }
                                                                                                                            setLoading(false)
                                                                                                                                }
                                                                                                                                    load()
                                                                                                                                      }, [])

                                                                                                                                        if (loading) return <div className="p-8 text-gray-500">Loading...</div>

                                                                                                                                          return (
                                                                                                                                              <div className="p-8">
                                                                                                                                                    <h1 className="text-2xl font-bold text-gray-900 mb-8">Reports</h1>
                                                                                                                                                          <div className="grid grid-cols-4 gap-6 mb-8">
                                                                                                                                                                  <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                            <p className="text-sm text-gray-500">Total</p>
                                                                                                                                                                                      <p className="text-3xl font-bold text-gray-900">{stats.total}</p>
                                                                                                                                                                                              </div>
                                                                                                                                                                                                      <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                                                                <p className="text-sm text-gray-500">Open</p>
                                                                                                                                                                                                                          <p className="text-3xl font-bold text-yellow-600">{stats.open}</p>
                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                          <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                                                                                                    <p className="text-sm text-gray-500">Closed</p>
                                                                                                                                                                                                                                                              <p className="text-3xl font-bold text-green-600">{stats.closed}</p>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                              <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-500">Overdue</p>
                                                                                                                                                                                                                                                                                                  <p className="text-3xl font-bold text-red-600">{stats.overdue}</p>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                                                                                                                                                                              <h2 className="font-semibold text-gray-900 mb-4">By Type</h2>
                                                                                                                                                                                                                                                                                                                                      {byType.length === 0 ? <p className="text-gray-500">No data.</p> : (
                                                                                                                                                                                                                                                                                                                                                <table className="w-full">
                                                                                                                                                                                                                                                                                                                                                            <thead><tr><th className="text-left text-xs font-medium text-gray-500 uppercase py-2">Type</th><th className="text-left text-xs font-medium text-gray-500 uppercase py-2">Count</th></tr></thead>
                                                                                                                                                                                                                                                                                                                                                                        <tbody>{byType.map(r => <tr key={r.type} className="border-t border-gray-100"><td className="py-2 text-sm text-gray-900">{r.type}</td><td className="py-2 text-sm font-medium text-gray-900">{r.count}</td></tr>)}</tbody>
                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                      }