import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

interface Template {
  id: string
    name: string
      subject: string
        body: string
          created_at: string
          }

          export default function TemplatesPage() {
            const [templates, setTemplates] = useState<Template[]>([])
              const [loading, setLoading] = useState(true)
                const [editing, setEditing] = useState<Template | null>(null)
                  const [form, setForm] = useState({ name: '', subject: '', body: '' })

                    useEffect(() => {
                        supabase.from('email_templates').select('*').order('name')
                              .then(({ data }) => { setTemplates(data || []); setLoading(false) })
                                }, [])

                                  const handleSave = async (e: React.FormEvent) => {
                                      e.preventDefault()
                                          if (editing) {
                                                await supabase.from('email_templates').update(form).eq('id', editing.id)
                                                      setTemplates(t => t.map(x => x.id === editing.id ? { ...x, ...form } : x))
                                                          } else {
                                                                const { data } = await supabase.from('email_templates').insert([{ ...form, tenant_id: 'default' }]).select().single()
                                                                      if (data) setTemplates(t => [...t, data])
                                                                          }
                                                                              setEditing(null)
                                                                                  setForm({ name: '', subject: '', body: '' })
                                                                                    }

                                                                                      const startEdit = (t: Template) => { setEditing(t); setForm({ name: t.name, subject: t.subject, body: t.body }) }

                                                                                        return (
                                                                                            <div className="p-8">
                                                                                                  <h1 className="text-2xl font-bold text-gray-900 mb-6">Email Templates</h1>
                                                                                                        <div className="grid grid-cols-3 gap-6">
                                                                                                                <div className="col-span-2">
                                                                                                                          {loading ? <div className="text-gray-500">Loading...</div> : (
                                                                                                                                      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                                                                                                                                                    <table className="w-full">
                                                                                                                                                                    <thead className="bg-gray-50">
                                                                                                                                                                                      <tr>
                                                                                                                                                                                                          <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Name</th>
                                                                                                                                                                                                                              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Subject</th>
                                                                                                                                                                                                                                                  <th className="px-6 py-3"></th>
                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                    </thead>
                                                                                                                                                                                                                                                                                                    <tbody className="divide-y divide-gray-100">
                                                                                                                                                                                                                                                                                                                      {templates.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                          <tr><td colSpan={3} className="px-6 py-8 text-center text-gray-500">No templates yet.</td></tr>
                                                                                                                                                                                                                                                                                                                                                            ) : templates.map(t => (
                                                                                                                                                                                                                                                                                                                                                                                <tr key={t.id} className="hover:bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                                                                      <td className="px-6 py-4 text-sm font-medium text-gray-900">{t.name}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                            <td className="px-6 py-4 text-sm text-gray-500">{t.subject}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-6 py-4"><button onClick={() => startEdit(t)} className="text-blue-600 text-sm hover:underline">Edit</button></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-xl border border-gray-200 p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="font-semibold text-gray-900 mb-4">{editing ? 'Edit Template' : 'New Template'}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSave} className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input placeholder="Template name" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input placeholder="Email subject" value={form.subject} onChange={e => setForm(f => ({ ...f, subject: e.target.value }))} className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <textarea placeholder="Email body..." value={form.body} onChange={e => setForm(f => ({ ...f, body: e.target.value }))} rows={6} className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" className="flex-1 bg-blue-600 text-white py-2 rounded-lg text-sm font-medium hover:bg-blue-700">Save</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {editing && <button type="button" onClick={() => { setEditing(null); setForm({ name: '', subject: '', body: '' }) }} className="px-4 py-2 border border-gray-300 rounded-lg text-sm">Cancel</button>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }